version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_prod
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
